### ISSUE TITLE
Migrate to vmware-tanzu

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/setup-action#52]
We are migrating all of the repos from the k14s org to vmware-tanzu. As part of this effort, we'd like to migrate this repo as well. Opening this issue as a place for us to collaborate to ensure that the migration of this repo goes smoothly.

**Comment by jbrunton** [comment]
@ewrenn8: sounds good! Lmk what I can do to assist.

**Comment by jbrunton** [comment]
@ewrenn8: do you have a preferred approach in mind? I haven't tried moving a GitHub action before, but I guess the options are:

1. Move the repo to the new org. However, I'm not sure what happens if you move a GitHub action. Will users of the old action still be able to use it? I know GitHub puts in place redirects when you transfer a repository, but I don't know if those are sufficient for actions. (EDIT: looks like this should be possible: https://github.community/t/transferring-github-action-to-another-owner/16581. So perhaps this is preferred? I'd need someone to do the transfer for me, to give me suitable permissions after the transfer, and to be on hand just in case it doesn't work out! This isn't from official docs, just a test someone did last May..)
2. Clone the repo. I could add a warning to this one prompting users to migrate. (This old version will continue to provide latest versions of apps from the Carvel repo in the meantime thanks to the redirects when the apps were moved from this org to vmware-tanzu.)

cc @cppforlife

**Comment by jbrunton** [comment]
I just published the latest version with the new name, so I think that's everything!

Closing this issue, but lmk if there's anything else I can assist with.
