### ISSUE TITLE
checksum of ytt is not working since 0.31.0

### ISSUE THREAD

**Issue by making** [carvel-dev/setup-action#65]
![image](https://user-images.githubusercontent.com/106908/104939484-cf9c8b00-59f3-11eb-99fe-c2b3d442e43a.png)

https://github.com/vmware-tanzu/carvel-ytt/releases/tag/v0.31.0

probably because the release note format has been changed

**Comment by jbrunton** [comment]
Thanks for the bug report! Should be a pretty simple fix, I'll submit a patch.

**Comment by jbrunton** [comment]
@making: this was in fact an error in the formatting of the release notes. @cppforlife just fixed that, so closing this issue.

**Comment by gcheadle-vmware** [comment]
Reopening this issue to track the work that is inflight to make sure this issue does not happen again. Waiting on PR to close this issue: https://github.com/vmware-tanzu/carvel-vendir/pull/44

**Comment by jbrunton** [comment]
@gcheadle-vmware: do you want to keep this issue open, or should it be closed / moved to another repo?

Happy to keep it open if it's helpful, I'm just not sure if anyone besides myself is actively monitoring this repo.

**Comment by gcheadle-vmware** [comment]
Hey @jbrunton, thank you for calling out this stale issue. We have included the change in ytt, kapp, imgpkg, and kbld, to ensure that this error will not happen again. For vendir and kapp-controller, I'm not sure what the current state is, but I think it would be appropriate to close this issue, since it is not being used to track any work.
